name: Terraform Verify

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  terraform-fmt-check:
    runs-on: ubuntu-latest
    name: Terraform fmt check

    steps:
      - uses: actions/checkout@v3

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Terraform fmt check
        working-directory: infrastructure
        run: terraform fmt -check -recursive

  terraform-validate:
    runs-on: ubuntu-latest
    name: Terraform validate

    steps:
      - uses: actions/checkout@v3

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Terraform init
        working-directory: infrastructure
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: infrastructure
        run: terraform validate